version: "3"

services:
  backend:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

